vim.o.guifont = "JetBrainsMono Nerd Font:h14" -- text below applies for VimScript
-- vim.g.neovide_fullscreen = true
vim.g.neovide_remember_window_size = true
vim.g.neovide_transparency = 0.8
vim.g.neovide_refresh_rate = 144
vim.g.neovide_cursor_animate_in_insert_mode = true
vim.g.neovide_cursor_animate_command_line = true
vim.g.neovide_cursor_smooth_blink = true
vim.g.neovide_cursor_vfx_mode = "ripple"
